"""GEval scoring node.

Scores generations against custom GEval metric specs, using either provided
``evaluation_steps`` or steps generated by ``geval_steps``.
"""

from __future__ import annotations

import asyncio
from typing import Optional

from deepeval.metrics import GEval
from deepeval.test_case import LLMTestCase, LLMTestCaseParams
from lumiseval_core.constants import METRIC_PASS_THRESHOLD
from lumiseval_core.geval_cache import (
    GEVAL_STEPS_PARSER_VERSION,
    GEVAL_STEPS_PROMPT_VERSION,
    compute_geval_signature,
)
from lumiseval_core.types import (
    GevalCostMeta,
    GevalMetricSpec,
    MetricCategory,
    MetricResult,
    NodeCostBreakdown,
)

from lumiseval_graph.llm.pricing import cost_usd, get_model_pricing
from lumiseval_graph.log import get_node_logger
from lumiseval_graph.nodes.metrics.base import BaseMetricNode

log = get_node_logger("geval")

_FIELD_TO_PARAM = {
    "question": LLMTestCaseParams.INPUT,
    "generation": LLMTestCaseParams.ACTUAL_OUTPUT,
    "reference": LLMTestCaseParams.EXPECTED_OUTPUT,
    "context": LLMTestCaseParams.CONTEXT,
}


class GevalNode(BaseMetricNode):
    """Evaluate generation quality against GEval metrics and evaluation steps."""

    node_name = "geval"
    prompt_version = GEVAL_STEPS_PROMPT_VERSION
    parser_version = GEVAL_STEPS_PARSER_VERSION

    @staticmethod
    def _missing_required_fields(
        *,
        metric: GevalMetricSpec,
        generation: str,
        question: Optional[str],
        reference: Optional[str],
        context: Optional[list[str]],
    ) -> list[str]:
        missing: list[str] = []
        for field_name in metric.record_fields:
            if field_name == "generation" and not (generation and generation.strip()):
                missing.append("generation")
            if field_name == "question" and not (question and question.strip()):
                missing.append("question")
            if field_name == "reference" and not (reference and reference.strip()):
                missing.append("reference")
            if field_name == "context" and not any(
                isinstance(item, str) and item.strip() for item in (context or [])
            ):
                missing.append("context")
        return missing

    async def _evaluate_metric(
        self,
        *,
        metric: GevalMetricSpec,
        generation: str,
        evaluation_steps: list[str],
        question: Optional[str],
        reference: Optional[str],
        context: Optional[list[str]],
    ) -> MetricResult:
        """Run one GEval scoring call for a single metric."""

        test_case = LLMTestCase(
            input=question or "",
            actual_output=generation,
            expected_output=reference or "",
            context=context or [],
        )
        g_eval = GEval(
            name=metric.name,
            criteria=metric.criteria
            or f"Evaluate this response for '{metric.name}' using the provided evaluation steps.",
            evaluation_steps=evaluation_steps,
            evaluation_params=[_FIELD_TO_PARAM[field_name] for field_name in metric.record_fields],
            model=self.judge_model,
        )
        await asyncio.get_event_loop().run_in_executor(None, g_eval.measure, test_case)

        score = g_eval.score or 0.0
        passed = score >= METRIC_PASS_THRESHOLD
        return MetricResult(
            name=metric.name,
            category=MetricCategory.ANSWER,
            score=score,
            passed=passed,
            reasoning=g_eval.reason or "",
        )

    def run(  # type: ignore[override]
        self,
        *,
        metrics: list[GevalMetricSpec],
        generation: str,
        question: Optional[str],
        reference: Optional[str],
        context: Optional[list[str]],
        steps_by_signature: dict[str, list[str]],
    ) -> list[MetricResult]:
        """Score each GEval metric; skip per-metric on missing required fields."""

        if not metrics:
            return []

        async def _run_all() -> list[MetricResult]:
            indexed_results: dict[int, MetricResult] = {}
            task_indices: list[int] = []
            tasks: list[asyncio.Future] = []

            for idx, metric in enumerate(metrics):
                missing_fields = self._missing_required_fields(
                    metric=metric,
                    generation=generation,
                    question=question,
                    reference=reference,
                    context=context,
                )
                if missing_fields:
                    indexed_results[idx] = MetricResult(
                        name=metric.name,
                        category=MetricCategory.ANSWER,
                        error=(
                            f"Skipped GEval metric due to missing required record fields: "
                            f"{', '.join(sorted(missing_fields))}."
                        ),
                    )
                    continue

                evaluation_steps = metric.evaluation_steps
                if not evaluation_steps:
                    if not metric.criteria:
                        indexed_results[idx] = MetricResult(
                            name=metric.name,
                            category=MetricCategory.ANSWER,
                            error="Skipped GEval metric because neither criteria nor evaluation_steps are available.",
                        )
                        continue
                    signature = compute_geval_signature(
                        criteria=metric.criteria,
                        model=self.judge_model,
                        prompt_version=self.prompt_version,
                        parser_version=self.parser_version,
                    )
                    evaluation_steps = steps_by_signature.get(signature)
                    if not evaluation_steps:
                        indexed_results[idx] = MetricResult(
                            name=metric.name,
                            category=MetricCategory.ANSWER,
                            error=(
                                f"Missing generated evaluation_steps for GEval metric signature "
                                f"'{signature}'."
                            ),
                        )
                        continue

                task_indices.append(idx)
                tasks.append(
                    asyncio.create_task(
                        self._evaluate_metric(
                            metric=metric,
                            generation=generation,
                            question=question,
                            reference=reference,
                            context=context,
                            evaluation_steps=evaluation_steps,
                        )
                    )
                )

            if tasks:
                evaluated = await asyncio.gather(*tasks)
                for idx, result in zip(task_indices, evaluated):
                    indexed_results[idx] = result

            return [indexed_results[i] for i in range(len(metrics))]

        results = asyncio.run(_run_all())
        log.info(f"GEval evaluated metrics={len(results)}")
        return results

    def cost_estimate(
        self,
        *,
        cost_meta: GevalCostMeta,
        **_ignored,
    ) -> NodeCostBreakdown:
        """Estimate GEval scoring cost (one call per record per GEval metric)."""

        if cost_meta.eligible_records == 0 or cost_meta.rule_count == 0:
            return NodeCostBreakdown(model_calls=0, cost_usd=0.0)

        pricing = get_model_pricing(self.judge_model)
        per_call_cost = cost_usd(cost_meta.avg_input_tokens, pricing, "input") + cost_usd(
            cost_meta.avg_output_tokens, pricing, "output"
        )
        total_calls = cost_meta.eligible_records * cost_meta.rule_count
        return NodeCostBreakdown(
            model_calls=total_calls,
            cost_usd=round(total_calls * per_call_cost, 6),
        )

    @staticmethod
    def cost_formula(cost_meta: GevalCostMeta) -> str:
        """Human-readable formula for GEval scoring cost."""

        calls = cost_meta.eligible_records * cost_meta.rule_count
        input_tokens = round(cost_meta.avg_input_tokens)
        output_tokens = round(cost_meta.avg_output_tokens)
        total_tokens = calls * (input_tokens + output_tokens)
        return (
            f"calls         = {calls}  ({cost_meta.eligible_records} recs × {cost_meta.rule_count} GEval metrics)\n"
            f"input_tokens  = {input_tokens} (GEval scoring overhead) tok/call\n"
            f"output_tokens = {output_tokens} (GEval scoring output) tok/call\n"
            f"total_tokens  = {calls} × ({input_tokens} + {output_tokens}) = {total_tokens} tok"
        )
