# Run smoke test:
#   python -m lumiseval_graph.nodes.metrics.rubric
"""
Rubric Evaluator Node — scores the generation against each Rubric using DeepEval GEval.

All rules are evaluated in parallel via asyncio.gather to minimize total wall-clock time.
Returns one MetricResult per rule (score = GEval confidence, passed = score >= 0.5).

TODO: Implement Rubric Extractor agent that auto-derives rules from reference documents.
"""

import asyncio

from deepeval.metrics import GEval
from deepeval.test_case import LLMTestCase, LLMTestCaseParams
from lumiseval_core.constants import (
    METRIC_PASS_THRESHOLD,
)
from lumiseval_core.types import (
    MetricCategory,
    MetricResult,
    NodeCostBreakdown,
    Rubric,
    RubricCostMeta,
)

from lumiseval_graph.llm.pricing import cost_usd, get_model_pricing
from lumiseval_graph.log import get_node_logger
from lumiseval_graph.nodes.metrics.base import BaseMetricNode

log = get_node_logger("rubric_eval")


class RubricNode(BaseMetricNode):
    """Evaluates a generation against a set of rubric rules using DeepEval GEval.

    GEval makes two LLM calls per rule on its first encounter:
      1. A **steps-generation call** — sends the rule criteria to the LLM and receives
         3–4 concrete evaluation steps. These steps are deterministic for a given rule
         and do not change across records.
      2. An **evaluation call** — sends the generated steps + the actual generation
         text and returns a score (0–1) and a reason.

    To avoid paying the steps-generation cost on every record, this node caches the
    generated steps keyed by ``rule.id`` after the first encounter. Subsequent records
    evaluated against the same rule skip the generation call entirely, reducing LLM
    calls from ``2 × N × R`` to ``R + N × R`` (where N = records, R = unique rules).

    The cache lives on the instance, so it persists across multiple ``run()`` calls
    within the same pipeline execution but is reset when a new ``RubricNode`` is
    instantiated.
    """

    node_name = "rubric"

    def __init__(self, judge_model: str = "gpt-4o-mini") -> None:
        super().__init__(judge_model=judge_model)
        # Maps rule.id → evaluation steps generated by GEval on first encounter.
        self._steps_cache: dict[str, list[str]] = {}

    async def _evaluate_rule(self, rule: Rubric, generation: str) -> MetricResult:
        """Evaluate one rubric rule against the generation.

        On the first call for a given rule, GEval generates evaluation steps via an
        LLM call and the result is stored in ``_steps_cache``. Subsequent calls for
        the same rule pass the cached steps directly, skipping the generation call.
        """
        criteria = f"{rule.statement}\n\nPass condition: {rule.pass_condition}"
        test_case = LLMTestCase(input="", actual_output=generation)

        cached_steps = self._steps_cache.get(rule.id)
        g_eval = GEval(
            name=rule.id,
            criteria=criteria,
            evaluation_steps=cached_steps,  # None on first call → GEval generates them
            evaluation_params=[LLMTestCaseParams.ACTUAL_OUTPUT],
            model=self.judge_model,
        )

        # GEval.measure is sync; run in thread to not block event loop
        await asyncio.get_event_loop().run_in_executor(None, g_eval.measure, test_case)

        # Capture steps after first measure() so future records skip the generation call
        if cached_steps is None and g_eval.evaluation_steps:
            self._steps_cache[rule.id] = g_eval.evaluation_steps
            # log.debug(f"  cached {len(g_eval.evaluation_steps)} steps for rule '{rule.id}'")

        score = g_eval.score or 0.0
        passed = score >= METRIC_PASS_THRESHOLD
        log.info(f"  [{'PASS' if passed else 'FAIL'}] {rule.id}  score={score:.3f}")

        return MetricResult(
            name=rule.id,
            category=MetricCategory.ANSWER,
            score=score,
            passed=passed,
            reasoning=g_eval.reason or "",
        )

    def run(  # type: ignore[override]
        self,
        *,
        generation: str,
        rubric: list[Rubric],
    ) -> list[MetricResult]:
        """Evaluate the generation against all rubric rules in parallel.

        Args:
            generation: The LLM-generated text to evaluate.
            rubric:     List of Rubric objects to check against the generation.

        Returns:
            One MetricResult per rubric rule, each scored 0.0–1.0.
        """
        if not rubric:
            return []

        async def _run_all() -> list[MetricResult]:
            tasks = [self._evaluate_rule(rule, generation) for rule in rubric]
            return await asyncio.gather(*tasks)

        return asyncio.run(_run_all())

    def cost_estimate(
        self,
        *,
        cost_meta: RubricCostMeta,
        **_ignored,
    ) -> NodeCostBreakdown:
        """Estimate LLM cost for rubric evaluation without running any calls.

        GEval makes two distinct LLM calls per rule:
          - **Steps-generation call** (paid once per unique rule, then cached):
            sends the rule criteria and receives 3–4 evaluation steps.
          - **Evaluation call** (paid once per record per rule):
            sends the cached steps + generation text and returns a score.

        If ``_steps_cache`` already holds steps for some rules (e.g. from a prior
        batch), those rules skip the generation call and only the evaluation call
        is counted.

        Args:
            eligible_records:  Number of records this node will process.
            rubric_rule_count: Total number of unique rubric rules to evaluate.

        Returns:
            NodeCostBreakdown with total judge_calls and cost_usd.
        """
        if cost_meta.eligible_records == 0 or cost_meta.rule_count == 0:
            return NodeCostBreakdown(model_calls=0, cost_usd=0.0)

        pricing = get_model_pricing(self.judge_model)
        cost_per_call = cost_usd(cost_meta.avg_input_tokens, pricing, "input") + cost_usd(
            cost_meta.avg_output_tokens, pricing, "output"
        )

        # Steps-generation: one call per uncached rule (skipped for already-cached rules)
        uncached_rules = max(0, cost_meta.rule_count - cost_meta.unique_rule_count)
        steps_gen_calls = uncached_rules

        # Evaluation: one call per record per rule (always paid)
        eval_calls = cost_meta.eligible_records * cost_meta.rule_count

        total_calls = steps_gen_calls + eval_calls
        return NodeCostBreakdown(
            model_calls=total_calls,
            cost_usd=round(total_calls * cost_per_call, 6),
        )

    @staticmethod
    def cost_formula(cost_meta: RubricCostMeta) -> str:
        steps_calls = max(0, cost_meta.rule_count - cost_meta.unique_rule_count)
        eval_calls = cost_meta.eligible_records * cost_meta.rule_count
        total_calls = steps_calls + eval_calls
        return (
            f"{cost_meta.unique_rule_count} unique rules (steps cached) + "
            f"{cost_meta.eligible_records} recs × {cost_meta.rule_count} rules = {total_calls} calls\n"
            f"  input_tokens  = {round(cost_meta.avg_input_tokens)} (geval internal overhead) tok/call\n"
            f"  output_tokens = {round(cost_meta.avg_output_tokens)} (geval internal overhead) tok/call"
        )
